- remove supervise sub-directory

diff --git a/init/sv b/init/sv
--- a/init/sv
+++ b/init/sv
@@ -15,14 +15,14 @@ check_service() {
 
 check_enabled_service() {
   check_service
-  if [ ! -d "/etc/svdir/enabled/${service}/supervise" ]
+  if [ ! -d "/etc/svdir/enabled/${service}" ]
   then
-    if [ -d "/etc/svdir/available/${service}" ]
-    then
-      echo "ERROR: service ${service} is disabled"
-    else
-      echo "ERROR: service ${service} not found"
-    fi
+    echo "ERROR: service ${service} is disabled"
+    exit 1
+  fi
+  if [ ! -d "/etc/svdir/available/${service}" ]
+  then
+    echo "ERROR: service ${service} not found"
     exit 1
   fi
 }
@@ -30,19 +30,19 @@ check_enabled_service() {
 case "${action}" in
   start)
     check_enabled_service
-    /usr/bin/printf "u" >/etc/svdir/enabled/${service}/supervise/control
-    /usr/bin/cat /etc/svdir/enabled/${service}/supervise/status
+    /usr/bin/printf "u" >/etc/svdir/enabled/${service}/control
+    /usr/bin/cat /etc/svdir/enabled/${service}/status
     ;;
   stop)
     check_enabled_service
-    /usr/bin/printf "d" >/etc/svdir/enabled/${service}/supervise/control
-    /usr/bin/cat /etc/svdir/enabled/${service}/supervise/status
+    /usr/bin/printf "d" >/etc/svdir/enabled/${service}/control
+    /usr/bin/cat /etc/svdir/enabled/${service}/status
     ;;
   status|st)
     check_service
-    if [ -d "/etc/svdir/enabled/${service}/supervise" ]
+    if [ -f "/etc/svdir/enabled/${service}/status" ]
     then
-      /usr/bin/cat /etc/svdir/enabled/${service}/supervise/status
+      /usr/bin/cat /etc/svdir/enabled/${service}/status
     else
       if [ -d "/etc/svdir/available/${service}" ]
       then
@@ -53,8 +53,7 @@ case "${action}" in
     fi
     ;;
   enable)
-    check_service
-    if [ ! -d "/etc/svdir/enabled/${service}/supervise" ]
+    if [ ! -d "/etc/svdir/enabled/${service}" ]
     then
       if [ ! -d "/etc/svdir/available/${service}" ]
       then
@@ -66,7 +65,7 @@ case "${action}" in
     ;;
   disable)
     check_enabled_service
-    /usr/bin/printf "d" >/etc/svdir/enabled/${service}/supervise/control
+    /usr/bin/printf "d" >/etc/svdir/enabled/${service}/control
     /usr/bin/rm -rf /etc/svdir/enabled/${service}
     ;;
   list)
