* rename etc/svdir to etc/svdir.d

diff --git a/init/sv b/init/sv
--- a/init/sv
+++ b/init/sv
@@ -8,15 +8,25 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 check_enabled_service() {
   if [ ! -d "/etc/svdir/${service}/supervise" ]
   then
-    echo "ERROR: service ${service} not found"
+    if [ -d "/etc/svdir.d/${service}" ]
+    then
+      echo "ERROR: service ${service} is disabled"
+    else
+      echo "ERROR: service ${service} not found"
+    fi
     exit 1
   fi
 }
 
 check_disabled_service() {
-  if [ ! -d "/etc/svdir/${service}.disable" ]
+  if [ -d "/etc/svdir/${service}/supervise" ]
   then
-    echo "ERROR: service ${service} is not disabled"
+    echo "ERROR: service ${service} is already enabled"
+    exit 1
+  fi
+  if [ ! -d "/etc/svdir.d/${service}" ]
+  then
+    echo "ERROR: service ${service} not found"
     exit 1
   fi
 }
@@ -44,12 +54,12 @@ case "${action}" in
     ;;
   enable)
     check_disabled_service
-    /usr/bin/mv /etc/svdir/${service}.disable /etc/svdir/${service}
+    /usr/bin/ln -s /etc/svdir.d/${service} /etc/svdir/${service}
     ;;
   disable)
     check_enabled_service
     /usr/bin/printf "d" >/etc/svdir/${service}/supervise/control
-    /usr/bin/mv /etc/svdir/${service} /etc/svdir/${service}.disable
+    /usr/bin/rm -rf /etc/svdir/${service}
     ;;
   *)
     echo "Usage: sv <down | up | status | enable | disable> service"
