- /lib/lsb/init-functions is deprecated

diff --git a/init/etc/startup.d/S13resolvconf b/init/etc/startup.d/S13resolvconf
--- a/init/etc/startup.d/S13resolvconf
+++ b/init/etc/startup.d/S13resolvconf
@@ -1,40 +1,10 @@
 #!/bin/sh
-
+PATH=/sbin:/bin
 [ -x /sbin/resolvconf ] || exit 0
 
-PATH=/sbin:/bin
 RUN_DIR=/run/resolvconf
 ENABLE_UPDATES_FLAGFILE="${RUN_DIR}/enable-updates"
 POSTPONED_UPDATE_FLAGFILE="${RUN_DIR}/postponed-update"
-
-. /lib/lsb/init-functions
-
-# $1 EXITSTATUS
-# [$2 MESSAGE]
-log_action_end_msg_and_exit()
-{
-	log_action_end_msg "$1" ${2:+"$2"}
-	exit $1
-}
-
-create_runtime_directories()
-{
-	umask 022
-	if [ ! -d "$RUN_DIR" ] ; then
-		# Create directory at the target
-		mkdir "$RUN_DIR" || log_action_end_msg_and_exit 1 "Error creating directory $RUN_DIR"
-	fi
-	[ -x /sbin/restorecon ] && /sbin/restorecon "$RUN_CANONICALDIR"
-
-	# The resolvconf run directory now exists.
-	if [ ! -d "${RUN_DIR}/interface" ] ; then
-		mkdir "${RUN_DIR}/interface" || log_action_end_msg_and_exit 1 "Error creating directory ${RUN_DIR}/interface"
-	fi
-	[ -x /sbin/restorecon ] && /sbin/restorecon "${RUN_DIR}/interface" "${RUN_DIR}/resolv.conf "${RUN_DIR}/enable-updates
-
-	# The interface directory now exists.  We are done.
-	return
-}
 
 wipe_runtime_directories()
 {
@@ -44,31 +14,33 @@ wipe_runtime_directories()
 	rm -f "$ENABLE_UPDATES_FLAGFILE"
 	rm -f "$POSTPONED_UPDATE_FLAGFILE"
 	rm -rf "${RUN_DIR}/interface/*"
-	return
 }
 
-case "$1" in
-  start)
-	# The "start" method should only be used at boot time.
-	# Don't run this on package upgrade, for example.
-	log_action_begin_msg "Setting up resolvconf"
-	# Wipe runtime directories in case they aren't on a tmpfs
-	wipe_runtime_directories
-	# Create runtime directories in case they are on a tmpfs
-	create_runtime_directories
-	# Request a postponed update (needed in case the base file has content).
-	:> "$POSTPONED_UPDATE_FLAGFILE" || log_action_end_msg_and_exit 1 "failed requesting update"
-	# Enable updates and perform the postponed update.
-	resolvconf --enable-updates || log_action_end_msg_and_exit 1 "failed to enable updates"
-	log_action_end_msg_and_exit 0
-	;;
-  stop)
-	# The "stop" method should only be used at shutdown time.
-	log_action_begin_msg "Stopping resolvconf"
-	resolvconf --disable-updates || log_action_end_msg_and_exit 1 "failed to disable updates"
-	log_action_end_msg_and_exit 0
-	;;
-esac
+create_runtime_directories()
+{
+	umask 022
+	# Create directory at the target
+  mkdir -p "$RUN_DIR"
+	if [ ! -d "$RUN_DIR" ] ; then
+		echo "Error creating directory $RUN_DIR"
+    exit 1
+	fi
+	# The resolvconf run directory now exists.
+  mkdir -p "${RUN_DIR}/interface"
+	if [ ! -d "${RUN_DIR}/interface" ] ; then
+		echo "Error creating directory ${RUN_DIR}/interface"
+    exit 1
+	fi
+	# The interface directory now exists.  We are done.
+}
 
-# Don't reach here
-exit 99
+echo "Setting up resolvconf"
+# Wipe runtime directories in case they aren't on a tmpfs
+wipe_runtime_directories
+# Create runtime directories in case they are on a tmpfs
+create_runtime_directories
+# Request a postponed update (needed in case the base file has content).
+:> "$POSTPONED_UPDATE_FLAGFILE" || echo "  failed requesting updates"
+# Enable updates and perform the postponed update.
+resolvconf --enable-updates || echo "  failed to enable updates"
+exit 0
