* refactoring networking

diff --git a/init/etc/startup.d/S14networking b/init/etc/startup.d/S14networking
--- a/init/etc/startup.d/S14networking
+++ b/init/etc/startup.d/S14networking
@@ -1,14 +1,9 @@
 #!/bin/sh -e
 
 PATH="/sbin:/bin"
-RUN_DIR="/run/network"
-IFSTATE="$RUN_DIR/ifstate"
-STATEDIR="$RUN_DIR/state"
 
 [ -x /sbin/ifup ] || exit 0
 [ -x /sbin/ifdown ] || exit 0
-
-. /lib/lsb/init-functions
 
 CONFIGURE_INTERFACES=yes
 EXCLUDE_INTERFACES=
@@ -16,137 +11,57 @@ VERBOSE=no
 
 [ -f /etc/default/networking ] && . /etc/default/networking
 
+if [ "$CONFIGURE_INTERFACES" = no ]
+then
+  echo "Not configuring network interfaces, see /etc/default/networking"
+  exit 0
+fi
+
+echo "Configuring network interfaces"
+set -- $EXCLUDE_INTERFACES
+exclusions=""
+for iface in $EXCLUDE_INTERFACES
+do
+  exclusions="-X $iface $exclusions"
+done
+echo "Excluding: $exclusions"
+
 verbose=""
 [ "$VERBOSE" = yes ] && verbose=-v
 
-process_exclusions() {
-    set -- $EXCLUDE_INTERFACES
-    exclusions=""
-    for d
-    do
-	exclusions="-X $d $exclusions"
-    done
-    echo $exclusions
-}
+echo "Check ifstate"
+RUN_DIR="/run/network"
+IFSTATE="$RUN_DIR/ifstate"
+if [ ! -d "$RUN_DIR" ] ; then
+  if ! mkdir -p "$RUN_DIR" ; then
+      echo "can't create $RUN_DIR"
+      exit 1
+  fi
+  if ! chown root:netdev "$RUN_DIR" ; then
+      echo "can't chown $RUN_DIR"
+  fi
+fi
+if [ ! -r "$IFSTATE" ] ; then
+  if ! :> "$IFSTATE" ; then
+      echo "can't initialise $IFSTATE"
+      exit 1
+  fi
+fi
 
-process_options() {
-    [ -e /etc/network/options ] || return 0
-    log_warning_msg "/etc/network/options still exists and it will be IGNORED! Please use /etc/sysctl.conf instead."
-}
+if [ -x /bin/udevadm ]; then
+  /bin/udevadm settle
+fi
 
-check_ifstate() {
-    if [ ! -d "$RUN_DIR" ] ; then
-	if ! mkdir -p "$RUN_DIR" ; then
-	    log_failure_msg "can't create $RUN_DIR"
-	    exit 1
-	fi
-	if ! chown root:netdev "$RUN_DIR" ; then
-	    log_warning_msg "can't chown $RUN_DIR"
-	fi
-    fi
-    if [ ! -r "$IFSTATE" ] ; then
-	if ! :> "$IFSTATE" ; then
-	    log_failure_msg "can't initialise $IFSTATE"
-	    exit 1
-	fi
-    fi
-}
+echo "Configuring auto interfaces"
+for iface in $(ifquery --list --allow=auto $exclusions)
+do
+  echo "Set network interface $iface up"
+  ifup $verbose $iface
+done
 
-check_network_file_systems() {
-    [ -e /proc/mounts ] || return 0
-
-    if [ -e /etc/iscsi/iscsi.initramfs ]; then
-	log_warning_msg "not deconfiguring network interfaces: iSCSI root is mounted."
-	exit 0
-    fi
-
-    while read DEV MTPT FSTYPE REST; do
-	case $DEV in
-	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*|curlftpfs*)
-	    log_warning_msg "not deconfiguring network interfaces: network devices still mounted."
-	    exit 0
-	    ;;
-	esac
-	case $FSTYPE in
-	nfs|nfs4|smbfs|ncp|ncpfs|cifs|coda|ocfs2|gfs|pvfs|pvfs2|fuse.httpfs|fuse.curlftpfs)
-	    log_warning_msg "not deconfiguring network interfaces: network file systems still mounted."
-	    exit 0
-	    ;;
-	esac
-    done < /proc/mounts
-}
-
-check_network_swap() {
-    [ -e /proc/swaps ] || return 0
-
-    while read DEV MTPT FSTYPE REST; do
-	case $DEV in
-	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-	    log_warning_msg "not deconfiguring network interfaces: network swap still mounted."
-	    exit 0
-	    ;;
-	esac
-    done < /proc/swaps
-}
-
-ifup_hotplug () {
-    if [ -d /sys/class/net ]
-    then
-	    ifaces=$(for iface in $(ifquery --list --allow=hotplug)
-			    do
-				    link=${iface%%:*}
-				    link=${link%%.*}
-				    if [ -e "/sys/class/net/$link" ] && ! ifquery --state "$iface" >/dev/null
-				    then
-					echo "$iface"
-				    fi
-			    done)
-	    if [ -n "$ifaces" ]
-	    then
-		ifup $ifaces "$@" || true
-	    fi
-    fi
-}
-
-case "$1" in
-start)
-	process_options
-	check_ifstate
-
-	if [ "$CONFIGURE_INTERFACES" = no ]
-	then
-	    log_action_msg "Not configuring network interfaces, see /etc/default/networking"
-	    exit 0
-	fi
-	set -f
-	exclusions=$(process_exclusions)
-	log_action_begin_msg "Configuring network interfaces"
-	if [ -x /bin/udevadm ]; then
-		if [ -n "$(ifquery --list --exclude=lo)" ] || [ -n "$(ifquery --list --allow=hotplug)" ]; then
-			/bin/udevadm settle || true
-		fi
-	fi
-	if ifup -a $exclusions $verbose && ifup_hotplug $exclusions $verbose
-	then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-stop)
-	check_network_file_systems
-	check_network_swap
-
-	log_action_begin_msg "Deconfiguring network interfaces"
-	if ifdown -a --exclude=lo $verbose; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-esac
-
-exit 0
-
-# vim: noet ts=8
+echo "Configuring hotplug interfaces"
+for iface in $(ifquery --list --allow=hotplug $exclusions)
+do
+  echo "Set network interface $iface up"
+  ifup $verbose $iface
+done
