+ replace /usr/bin with /bin

diff --git a/init/etc/startup.d/S17utmp b/init/etc/startup.d/S17utmp
--- a/init/etc/startup.d/S17utmp
+++ b/init/etc/startup.d/S17utmp
@@ -1,13 +1,11 @@
 #!/bin/sh
-
-PATH=/usr/sbin:/usr/bin:/sbin:/bin
 echo "Initialize utmp"
-readonly utmp='/var/run/utmp'
+utmp='/run/utmp'
 if > "${utmp}" ; then
-	chgrp utmp "${utmp}" || echo "Failed to chgrp ${utmp}"
-	chmod 664  "${utmp}" || echo "Failed to chmod ${utmp}"
-	return 0
+    /bin/chgrp utmp "${utmp}" || echo "Failed to chgrp ${utmp}"
+    /bin/chmod 664  "${utmp}" || echo "Failed to chmod ${utmp}"
+    return 0
 else
-	echo "Failed to truncate ${utmp}"
-	return 1
+    echo "Failed to truncate ${utmp}"
+    return 1
 fi
